"""initial schema

Revision ID: 92139b4ddec7
Revises: 
Create Date: 2026-08-21 14:33:57.220529
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '92139b4ddec7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_invoice_ref_normalized', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supplier_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sap_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_blocking_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_step', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('approval_owner_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('clearing_document', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_document', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_proof_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_cache_invoice_ref'), 'invoice_cache', ['invoice_ref'], unique=False)
    op.create_index(op.f('ix_invoice_cache_sap_id'), 'invoice_cache', ['sap_id'], unique=False)
    op.create_index(op.f('ix_invoice_cache_stage'), 'invoice_cache', ['stage'], unique=False)
    op.create_index(op.f('ix_invoice_cache_status'), 'invoice_cache', ['status'], unique=False)
    op.create_index(op.f('ix_invoice_cache_supplier_invoice_ref_normalized'), 'invoice_cache', ['supplier_invoice_ref_normalized'], unique=False)
    op.create_index(op.f('ix_invoice_cache_supplier_name'), 'invoice_cache', ['supplier_name'], unique=False)
    op.create_table('routing_rules',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_rules_domain'), 'routing_rules', ['domain'], unique=False)
    op.create_index(op.f('ix_routing_rules_email'), 'routing_rules', ['email'], unique=False)
    op.create_table('senders',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vendor_sap_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_senders_email'), 'senders', ['email'], unique=True)
    op.create_index(op.f('ix_senders_vendor_sap_id'), 'senders', ['vendor_sap_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sender_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('assigned_operator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_thread_continuation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_assigned_operator_id'), 'tickets', ['assigned_operator_id'], unique=False)
    op.create_index(op.f('ix_tickets_message_id'), 'tickets', ['message_id'], unique=True)
    op.create_index(op.f('ix_tickets_sender_email'), 'tickets', ['sender_email'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_index(op.f('ix_tickets_thread_id'), 'tickets', ['thread_id'], unique=False)
    op.create_table('audit_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('node', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_action'), 'audit_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_entries_node'), 'audit_entries', ['node'], unique=False)
    op.create_index(op.f('ix_audit_entries_ticket_id'), 'audit_entries', ['ticket_id'], unique=False)
    op.create_table('response_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('edited_by_human', sa.Boolean(), nullable=False),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('attach_invoice_pdf', sa.Boolean(), nullable=False),
    sa.Column('attach_payment_proof', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_drafts_ticket_id'), 'response_drafts', ['ticket_id'], unique=False)
    op.create_table('human_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operator_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['response_drafts.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_reviews_draft_id'), 'human_reviews', ['draft_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_operator_id'), 'human_reviews', ['operator_id'], unique=False)
    op.create_index(op.f('ix_human_reviews_ticket_id'), 'human_reviews', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_reviews_ticket_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_operator_id'), table_name='human_reviews')
    op.drop_index(op.f('ix_human_reviews_draft_id'), table_name='human_reviews')
    op.drop_table('human_reviews')
    op.drop_index(op.f('ix_response_drafts_ticket_id'), table_name='response_drafts')
    op.drop_table('response_drafts')
    op.drop_index(op.f('ix_audit_entries_ticket_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_node'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_action'), table_name='audit_entries')
    op.drop_table('audit_entries')
    op.drop_index(op.f('ix_tickets_thread_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_sender_email'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_message_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_assigned_operator_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_senders_vendor_sap_id'), table_name='senders')
    op.drop_index(op.f('ix_senders_email'), table_name='senders')
    op.drop_table('senders')
    op.drop_index(op.f('ix_routing_rules_email'), table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_domain'), table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_invoice_cache_supplier_name'), table_name='invoice_cache')
    op.drop_index(op.f('ix_invoice_cache_supplier_invoice_ref_normalized'), table_name='invoice_cache')
    op.drop_index(op.f('ix_invoice_cache_status'), table_name='invoice_cache')
    op.drop_index(op.f('ix_invoice_cache_stage'), table_name='invoice_cache')
    op.drop_index(op.f('ix_invoice_cache_sap_id'), table_name='invoice_cache')
    op.drop_index(op.f('ix_invoice_cache_invoice_ref'), table_name='invoice_cache')
    op.drop_table('invoice_cache')
    # ### end Alembic commands ###
